#!/usr/bin/bash

#Install dependencies

# oryx build -p virtualenv_name=.venv --log-file /tmp/oryx-build.log --manifest-dir /tmp || echo 'Could not auto-build. Skipping.'

echo "Installing Zowe CLI"
npm install -g @zowe/cli@latest; zowe config reset CredentialManager
echo "Installing Zowe CLI plugin @broadcom/endevor-for-zowe-cli"
zowe plugins install @broadcom/endevor-for-zowe-cli@latest
echo "Installing Zowe CLI plugin @broadcom/endevor-bridge-for-git-for-zowe-cli"
zowe plugins install @broadcom/endevor-bridge-for-git-for-zowe-cli@latest

# Java v8
source /usr/local/sdkman/bin/sdkman-init.sh
echo "Installing Java 8"
sdk install java 8.0.302-open
echo "Setting up Java 8"
sdk use java 8.0.302-open

# Project dependencies
echo "Installing npm project dependencies"
npm ci
